# Generated by Django 4.1.7 on 2023-03-26 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_comic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='price',
        ),
    ]
